version: '3'
services:
  api:
    build: .
    command: bash -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000"
    depends_on:
      - postgres
    ports:
      - 8000:8000
    env_file:
      - ./.env
    # Overwriting DB_HOSTNAME from .env to match docker network hostname
    environment:
      - DB_HOSTNAME=postgres
  postgres:
    image: postgres
    env_file:
      - ./.env
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db:
    

